language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"

install:
  - pip install -r requirements/testing.txt
  - pip install coveralls

script:
  - make lint
  - make coverage

after_success:
  - coveralls